development: &default
  mode: sandbox
  client_id: EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
  client_secret: EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM
  # # with Proxy
  # http_proxy: http://proxy-ipaddress:3129/
  # # with CA File
  # ssl_options:
  #   ca_file: config/cacert.pem
  # # Override Endpoint
  # rest_endpoint: https://api.sandbox.paypal.com
test:
  <<: *default
production:
  mode: live
  client_id: ATxxEBlZKvBPJEVwAeZSkdNASEgKSfkJx_xSfgYeM3WY2J0n5d5r4QsXzLtlOt1RxE5k1upm-OiJukGU
  client_secret: EERC4Qthr6JqP88e90yev4e511EDlieZ5vOIO7ph1vvvqtspcfUmb2udxAJM9mPkfuXtO_e6acOOb583