development: &default
  mode: sandbox
  client_id: <%= ENV["PAYPAL_SANDBOX_CLIENT_ID"] %>
  client_secret: <%= ENV["PAYPAL_SANDBOX_CLIENT_SECRET"] %>
  # # with Proxy
  # http_proxy: http://proxy-ipaddress:3129/
  # # with CA File
  # ssl_options:
  #   ca_file: config/cacert.pem
  # # Override Endpoint
  # rest_endpoint: https://api.sandbox.paypal.com
test:
  <<: *default
production:
  mode: live
  client_id: <%= ENV["PAYPAL_CLIENT_ID"] %>
  client_secret: <%= ENV["PAYPAL_CLIENT_SECRET"] %>